-- AlterTable
ALTER TABLE "Asset" ADD COLUMN     "address" TEXT,
ADD COLUMN     "builtSize" DOUBLE PRECISION,
ADD COLUMN     "closerCommission" DOUBLE PRECISION,
ADD COLUMN     "constructionEnd" TIMESTAMP(3),
ADD COLUMN     "constructionStart" TIMESTAMP(3),
ADD COLUMN     "downPaymentAmount" TEXT,
ADD COLUMN     "exitLiquidity" TEXT,
ADD COLUMN     "facilityManagement" BOOLEAN,
ADD COLUMN     "firstPayoutDate" TIMESTAMP(3),
ADD COLUMN     "fractionTotal" INTEGER,
ADD COLUMN     "installmentPeriods" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "landSize" DOUBLE PRECISION,
ADD COLUMN     "leadCommission" DOUBLE PRECISION,
ADD COLUMN     "managementMode" TEXT,
ADD COLUMN     "markup" TEXT,
ADD COLUMN     "offPlanDiscount" DOUBLE PRECISION,
ADD COLUMN     "offPlanSecurity" TEXT,
ADD COLUMN     "operatingCost" DOUBLE PRECISION,
ADD COLUMN     "ownershipType" TEXT,
ADD COLUMN     "paymentOptions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "propertyCategory" TEXT,
ADD COLUMN     "referenceCode" TEXT,
ADD COLUMN     "rentalFrequency" TEXT,
ADD COLUMN     "stageBasedDiscount" DOUBLE PRECISION,
ADD COLUMN     "unitConfiguration" TEXT;
